security:

    password_hashers:
        App\Entity\Users: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: email

    role_hierarchy:
        ROLE_ADMIN: [ROLE_DEVELOPPEUR,ROLE_CHEF_PROJET]
        ROLE_CHEF_PROJET: [ROLE_DEVELOPPEUR]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_connexion
                check_path: app_connexion
                username_parameter: email
                password_parameter: password
                default_target_path: app_home
            logout:
                path: app_deconnexion
                target: app_bienvenue


    access_control: 
        - { path: ^/, roles: PUBLIC_ACCESS }
        - { path: ^/connexion, roles: PUBLIC_ACCESS }
        - { path: ^/inscription, roles: PUBLIC_ACCESS }
        - { path: ^/projet, roles: ROLE_DEVELOPPEUR }
        - { path: ^/projet/show, roles: ROLE_DEVELOPPEUR }
        - { path: ^/projet/add, roles: ROLE_CHEF_PROJET }
        - { path: ^/projet/edit, roles: ROLE_CHEF_PROJET }
        - { path: ^/projet/delete, roles: ROLE_CHEF_PROJET }
        - { path: ^/tache, roles: ROLE_DEVELOPPEUR }
        - { path: ^/tache/add, roles: ROLE_CHEF_PROJET }
        - { path: ^/tache/delete, roles: ROLE_CHEF_PROJET }
        - { path: ^/list, roles: ROLE_DEVELOPPEUR }
        - { path: ^/show, roles: ROLE_CHEF_PROJET }
        - { path: ^/users/delete, roles: ROLE_CHEF_PROJET }
    