security:

    password_hashers:
        App\Entity\Users: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_connexion
                check_path: app_connexion
                username_parameter: email
                password_parameter: password
                default_target_path: app_home
            logout:
                path: app_logout
                target: app_bienvenue

    access_control: []